Create Utility function to check if folder/file exists or not, if not create that folder/file
rebaseteams/static-api-main pull request #77
Opened 2021-11-24 05:27 UTC by 100rabhpawar

Story details: https://app.shortcut.com/rebase-it-labs/story/481

2021-11-24 07:09 UTC, prasanarebase requested changes

2021-11-24 07:09 UTC, prasanarebase commented on src/utils/fileCheck.ts
> +    fs.writeFileSync(path, JSON.stringify(data));
will the data always be JSON?

2021-11-24 07:09 UTC, prasanarebase commented on src/utils/fileCheck.ts
> +  if (!fs.existsSync(path)) {
Add comments what this is doing

2021-11-24 07:09 UTC, prasanarebase commented on src/utils/fileCheck.ts
> +// TO check if file/folder exists or not, if not create file/folder.
Add test case

2021-11-24 07:20 UTC, prasanarebase requested changes

2021-11-24 07:20 UTC, prasanarebase commented on src/utils/fileCheck.ts
> +  if (!fs.existsSync('./database')) {
why is this checking database folder with static value

2021-11-25 11:01 UTC, praveenrebase approved these changes

2021-11-25 11:02 UTC, merged